In [1]:
import numpy as np

# Numpy Assessment of Skills

This is designed for our lab to test *how well* you are able to use numpy. This means not simply being able to store data in a numpy `NdArray` but rather being able to use numpy efficiently to be able to cut out `for` loops and similar.

I design these questions not be be extensive nor to be done closed-book: you should be searching through numpy documentation even routinely while developing, so please do not hesistate to Google the answers if you need to. 

In addition, I will primarily be checking syntax on these examples. I would expect generally a solution which *only* involves Numpy and **Does not involve loops**.

If any exercises are confusing please let me know. My plan is to use this as an onboarding guide in future semesters for Radiation Therapy, so it is best to refine it now

Topics
* Get row or column
* Sum across axis
* Numpy mean
* Numpy expand dims and its relation to adding new arrays
* Inplace ops = x = x / 2. vs x /= 2.
* `np.where()`
* `np.count_nonzero`
* `np.repeat()` -> Nearest Neighbor Upscaling
* Shape tuple in numpy vs len(array)
* [-1] index
* Boolean indexing
* Bitwise `AND`and `OR`
* Concatenate

### Question 0: Basic Stuff

Each bullet point should be solved in 1 line of code in the code box below.

* Print the datatype of `basic_q`
* Print the shape of `basic_q`. What type of variable is the shape of `basic_q`?
* Create an array of zeros with 20 rows and 4 columns of type `np.float32`, named `zeros_array`
* Create an array of ones with the same shape of `zeros_array`. You should not be hardcoding the values `20` or `4` in your solution. 

In [2]:
# Your code here
basic_q = np.zeros(shape=(3,3))


### Question 1: Summation of column

Consider the array `sum_array` below. Please sum all the values in the first column, and print the sum to the screen

In [3]:
sum_array = np.random.randint(low=0, high=10, size=(4,4))
print(sum_array)

# Your code starts here

[[6 1 3 0]
 [2 1 6 7]
 [2 9 1 6]
 [2 9 5 1]]


### Question 2: Grayscale Conversion.

We define an arbitrary RGB image `rgb` below. It is modeled as an `np.uint8` array. 

**Q1** What is the maximum value that can be stored in an `np.uint8` array?

**Coding** Convert `rgb` to it's grayscale representation. The last axis represents the channels of the image, where `rgb[0]` is the R channel. Remember that RGB -> Grayscale is done by taking the linear average of the R, G, and B channels for each pixel location. Then print the array to the screen.

In [4]:
rgb = np.random.randint(low=0, high=255, size=(3,4,4), dtype=np.uint8)
print(rgb)

# Your code starts here

[[[126 113  20  71]
  [133  28 198 150]
  [225  21 100 223]
  [210  80 215 169]]

 [[ 10 224 229  21]
  [ 84 183  53  80]
  [ 25 122 239   0]
  [251  96 167 134]]

 [[134  23 122 201]
  [202  86  87 104]
  [208 156 150  30]
  [179 230  19   1]]]


### Question 3: Average Test Scores

Consider the array `test_scores`. Each row represents a student, and each column represents a test. For example, `test_scores[0, 0]` represents the test scores for the 1st student on the 1st test.

Find the average test score per student

In [5]:
test_scores = np.random.randint(0, 100, size=(5,3), dtype=np.int)
print(test_scores)

# Your code starts here

[[ 7 17 94]
 [67 85 65]
 [ 2  2 61]
 [84 44 82]
 [65 87 14]]


### Question 4: Setting values with dimensions

Consider the array `setter` below. I am looking to set it's 2nd row to `[1, 2, 3]` so that it looks like

1 1 1

1 2 3

1 1 1

Please uncomment and fill the line of code below. Do not modify anything to the left hand side of the equals sign, only add your code to the right hand side.

In [6]:
setter = np.ones(shape=(3,3), dtype=np.uint8)
# setter[1:2] = 

### Question 5: Concatenating Two Arrays

Please concatenate the two arrays `ones` and `zeros` so that the complete array looks like
```
1 1 1 1 

0 0 0 0
```

In [7]:
ones = np.ones(shape=(4,), dtype=np.float32)
zeros = np.zeros(shape=(4,), dtype=np.float32)

# Add code here

### Question 6: Floating Point Division of Integers

Uncomment the line of code below and see it fail. Why does it fail? Correct the line so that the operation is performed correctly.

In [8]:
new_ones = np.ones(shape=(4,), dtype=np.int)
# new_ones /= 2.

### Question 7: Sparse Arrays

The array `sparse` is an array of zeros and ones. Convert the array so that instead of being an array of zeros and ones, it is the indices corresponding to the rows and columns of each 1 in the array

For example:

0 0

1 1 

Becomes

1 0

1 1

Where each row corresponds to a (row, col) coordinate of the point in the original array `sparse`

In [9]:
sparse = np.zeros(shape=(2,2), dtype=np.int8)
sparse[1] = 1
print(sparse)

# Your code here

[[0 0]
 [1 1]]


### Question 8: Intersection over Union

Consider the two arrays below, `annotation` and `prediction`. Calculate the intersection over union (IU) of the two arrays. 

IU = (Area of Overlap) / (Area of Union)

(Area of Overlap) = total number of indices where both `annotation` and `prediction` have 1s

(Area of Union) = total number of indices where *either* `annotation` or `prediction` have 1s

In [10]:
annotation = np.array([1, 0, 0, 1])
prediction = np.array([1, 1, 0, 0])

# your code here

### Question 9: Nearest Neighbor Upscaling

Perform the nearest neighbor 2x upscaling of the following array. The original array will be
```
1 2 
3 4
```

The nearest neighbor upscaling will convert it to
```
1 1 2 2
1 1 2 2
3 3 4 4
3 3 4 4
```

You **may not** declare another array and fill the values in. I also reiterate that you **may not** use `for` loops during this question. 

In [11]:
nn = np.array([[1, 2], [3, 4]], dtype=np.int)
print(nn)

# your code here

[[1 2]
 [3 4]]


### Question 10: Difference in Shape 

What is the difference between `len(shape_array)` and `shape_array.shape`? Try it out below

In [12]:
shape_array = np.zeros(shape=(10, 20, 3), dtype=np.float32)

### Question 11: Variable Binarization

Consider the array `binary`. It will consist of two numbers- 1, and a randomly selected number greater than 1. Count how many times the other number appears in the array `binary`. Note you should not be hardcoding a value when determining the non-one value. 

In [13]:
binary = np.ones((5,5),dtype=np.int8)
random_value = np.random.randint(2, 10) 
binary[:, 0] = random_value
binary[0, :] = random_value

# Your code here

### Question 12: Functions and Numpy

Consider the function `adds_two` below. What effect will it have on `a`? Why is this the case? What would happen if `a` was not an `NdArray` but rather a generic python `int`? Try it out below. Note that for this question, I am looking for a verbal answer. You can double click on this text, and a box should pop up in Jupyter Notebook, so you can add your answer directly inside the text box.

ANSWER STARTS HERE:


In [14]:
def adds_two(a):
    """
    Adds two to either an integer or numpy array
    
    Parameters
    ----------
    a : NdArray or int
        Variable to add 2 to
    """
    a += 2

a = np.ones(shape=(2,2), dtype=np.int)
a_integer = 1


### Question 13: Odd Mean

Find the mean of all odd numbers in the array `odd_mean` below

In [15]:
odd_mean = np.random.randint(0, 10, size=(4,4), dtype=np.int)
print(odd_mean)

# Your code here

[[5 5 9 4]
 [3 2 0 7]
 [1 6 2 2]
 [8 1 1 3]]


### Question 14: Array Reversal

Reverse the array `a = [1 2 3 4 5]` so that `a = [5 4 3 2 1]`. This should be done in one line of code.

In [16]:
a = np.array([1, 2, 3, 4, 5])

# Your code here

### Question 15: Datatype Conversions of Arrays

consider the code section in the box below. What is printed by the commented out line? Why is this the case? Note that your answer should be written as this solves itself trivially if you just uncomment the line.

YOUR ANSWER HERE:

In [17]:
original_array = np.array([1, 2, 3, 4, 5], dtype=np.float32)
new_array = np.uint8(original_array)
new_array[2] = 10
# print(original_array[2])

### Question 16: Finding the Max Value

Find the index of the max value in `max_array`. This should be solved in 1 line of code.

In [18]:
max_array = np.random.randint(low=0, high=10000000000, size=(10, 10, 2))

# Your line of code below